name: Enter Container

on: [push]

jobs:
  container-open:
    runs-on: ubuntu-24.04
    container:
      image: biodepot/bwb:latest
      ports:
        - 6080
      volumes:
        - .:/data
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/.X11-unix:/tmp/.X11-unix
      options: |
        --privileged
        --group-add root
        
    steps:
      - name: Check local file system
        run: |
          ls
